//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form
    {
        public Form()
        {
            this.Expenses = new HashSet<Expense>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid OwnerId { get; set; }
        public string Description { get; set; }
        public string ManagerDescription { get; set; }
        public int Total { get; set; }
        public System.Guid StateId { get; set; }
    
        public virtual ICollection<Expense> Expenses { get; set; }
        public virtual State State { get; set; }
        public virtual User User { get; set; }
    }
}
